-- Run as the current wallet-connected Autonomous Database application user.
CREATE TABLE ro_users (id VARCHAR2(36) PRIMARY KEY, email VARCHAR2(320) UNIQUE NOT NULL, display_name VARCHAR2(120) NOT NULL, created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL);
CREATE TABLE ro_otp_requests (id VARCHAR2(36) PRIMARY KEY, email VARCHAR2(320) NOT NULL, otp_hash VARCHAR2(128) NOT NULL, expires_at TIMESTAMP WITH TIME ZONE NOT NULL, attempts NUMBER(3) DEFAULT 0 NOT NULL, created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL);
CREATE TABLE ro_sessions (id VARCHAR2(36) PRIMARY KEY, user_id VARCHAR2(36) NOT NULL REFERENCES ro_users(id), jd CLOB NOT NULL CHECK (length(jd)>0), state_json CLOB CHECK (state_json IS JSON), status VARCHAR2(32) NOT NULL, evaluator_model VARCHAR2(80) NOT NULL, writer_model VARCHAR2(80) NOT NULL, best_version_id VARCHAR2(36), created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL, updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL);
CREATE TABLE ro_documents (id VARCHAR2(36) PRIMARY KEY, session_id VARCHAR2(36) NOT NULL REFERENCES ro_sessions(id) ON DELETE CASCADE, kind VARCHAR2(16) NOT NULL CHECK (kind IN ('SOURCE','GENERATED')), filename VARCHAR2(255) NOT NULL, mime_type VARCHAR2(100) NOT NULL, content BLOB NOT NULL, created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL);
CREATE TABLE ro_resume_versions (id VARCHAR2(36) PRIMARY KEY, session_id VARCHAR2(36) NOT NULL REFERENCES ro_sessions(id) ON DELETE CASCADE, parent_version_id VARCHAR2(36), version_no NUMBER(10) NOT NULL, sections_json CLOB NOT NULL CHECK (sections_json IS JSON), resume_text CLOB NOT NULL, ats_score NUMBER(3), ats_breakdown_json CLOB CHECK (ats_breakdown_json IS JSON), evaluator_score NUMBER(3), grounding_valid CHAR(1) CHECK (grounding_valid IN ('Y','N')), created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL);
CREATE TABLE ro_evaluator_messages (id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, session_id VARCHAR2(36) NOT NULL REFERENCES ro_sessions(id) ON DELETE CASCADE, sequence_no NUMBER(10) NOT NULL, role VARCHAR2(16) NOT NULL CHECK (role IN ('system','user','model')), content CLOB NOT NULL, created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL, CONSTRAINT ro_msg_uq UNIQUE(session_id, sequence_no));
CREATE TABLE ro_evaluations (id VARCHAR2(36) PRIMARY KEY, session_id VARCHAR2(36) NOT NULL REFERENCES ro_sessions(id) ON DELETE CASCADE, version_id VARCHAR2(36), evaluation_json CLOB NOT NULL CHECK (evaluation_json IS JSON), score_delta NUMBER(5,2), created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL);
CREATE TABLE ro_improvement_items (id VARCHAR2(120) PRIMARY KEY, session_id VARCHAR2(36) NOT NULL REFERENCES ro_sessions(id) ON DELETE CASCADE, evaluation_id VARCHAR2(36) REFERENCES ro_evaluations(id), priority VARCHAR2(16), target_section VARCHAR2(64), source_evidence CLOB, jd_evidence CLOB, recommendation CLOB NOT NULL, approval_status VARCHAR2(16) DEFAULT 'PENDING', resolution_status VARCHAR2(16) DEFAULT 'OPEN');
CREATE TABLE ro_rate_limits (client_key VARCHAR2(64) PRIMARY KEY, window_started_at TIMESTAMP WITH TIME ZONE NOT NULL, request_count NUMBER(3) NOT NULL CHECK (request_count >= 0), updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL);
CREATE TABLE ro_migrations (version VARCHAR2(40) PRIMARY KEY, applied_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL);
CREATE INDEX ro_otp_email_idx ON ro_otp_requests(email); CREATE INDEX ro_sessions_user_idx ON ro_sessions(user_id); CREATE INDEX ro_versions_session_idx ON ro_resume_versions(session_id); CREATE INDEX ro_eval_messages_session_idx ON ro_evaluator_messages(session_id, sequence_no);
