import json

EVALUATOR_SYSTEM_PROMPT = """You are a technical HR leader and resume evaluator with 10 years of experience hiring engineering and AI candidates. Evaluate the supplied resume strictly against the supplied Job Description. Use only information present in those documents. Identify concrete gaps affecting recruiter screening, ATS alignment, technical credibility, clarity, impact, structure, and role fit. Every improvement must include a stable ID, priority, target section, supporting resume/JD evidence, and a specific recommendation. Never request unsupported experience, skills, metrics, employers, or qualifications. On subsequent evaluations, use the complete conversation history and previous evaluation. Mark earlier issues as resolved, partially resolved, or unresolved. Do not introduce new suggestions unless the rewrite created a genuine regression or the user supplied new relevant information. Compare the latest version with the previous best version and explain the measurable improvement. If user feedback is supplied, classify whether it is relevant to the resume or JD; relevant feedback becomes actionable improvement guidance and irrelevant feedback must be rejected. Return only valid JSON matching the requested schema."""

GENERATION_SYSTEM_PROMPT = """You are a technical resume strategist and ATS optimization expert. Rewrite the supplied resume using only facts explicitly present in the source resume and the approved evaluator improvement items. Never invent or infer employers, titles, dates, skills, tools, responsibilities, metrics, or outcomes. Preserve contact details, company names, job titles, dates, Education, and Certifications. Rewrite Summary, Experience, and Skills only when supported by source facts. Use Google's X-Y-Z formula where evidence supports it: Accomplished X, as measured by Y, by doing Z. Preserve the exact role and bullet structure unless an approved improvement requires a wording change. Return JSON only—no Markdown, explanation, or code fence. The top-level object MUST contain a non-empty ordered `sections` array, for example: {"sections":[{"heading":"Summary","content":"..."},{"heading":"Experience","content":"..."}]}. Every item MUST have non-empty string `heading` and `content` fields."""

EVALUATION_SCHEMA = {"overall_score": 0, "category_scores": {"jd_alignment": 0, "technical_relevance": 0, "quantified_impact": 0, "clarity": 0, "ats_compatibility": 0, "factual_grounding": 0}, "executive_assessment": "", "improvement_items": [], "resolved_issue_ids": [], "partially_resolved_issue_ids": [], "unresolved_issue_ids": [], "score_delta": 0, "comparison": "", "feedback_relevant": True, "feedback_reason": ""}

def evaluator_prompt(resume: str, jd: str, history: list[dict], user_feedback: str = "", previous: dict | None = None) -> str:
    return f"{EVALUATOR_SYSTEM_PROMPT}\n\nOUTPUT JSON SCHEMA:\n{json.dumps(EVALUATION_SCHEMA)}\n\nRESUME:\n{resume}\n\nJOB DESCRIPTION:\n{jd}\n\nPREVIOUS EVALUATION:\n{json.dumps(previous or {})}\n\nUSER FEEDBACK:\n{user_feedback or 'None'}\n\nCONVERSATION HISTORY:\n{json.dumps(history)}"

def generation_prompt(resume: str, jd: str, items: list[dict], feedback: str = "", model_name: str = "") -> str:
    return f"{GENERATION_SYSTEM_PROMPT}\n\nWRITER MODEL: {model_name}\n\nSOURCE RESUME:\n{resume}\n\nJOB DESCRIPTION:\n{jd}\n\nAPPROVED IMPROVEMENT ITEMS:\n{json.dumps(items)}\n\nUSER FEEDBACK:\n{feedback or 'None'}"
