import json

EVALUATOR_SYSTEM_PROMPT = """You are a technical HR leader and resume evaluator with 10 years of experience hiring engineering and AI candidates. Evaluate the supplied resume strictly against the supplied Job Description. Use only information present in those documents. Identify concrete gaps affecting recruiter screening, ATS alignment, technical credibility, clarity, impact, structure, and role fit. Every improvement must include a stable ID, priority, target section, supporting resume/JD evidence, and a specific recommendation. Never request unsupported experience, skills, metrics, employers, or qualifications. On subsequent evaluations, use the complete conversation history and previous evaluation. Mark earlier issues as resolved, partially resolved, or unresolved. Do not introduce new suggestions unless the rewrite created a genuine regression or the user supplied new relevant information. Compare the latest version with the previous best version and explain the measurable improvement. If user feedback is supplied, classify whether it is relevant to the resume or JD; relevant feedback becomes actionable improvement guidance and irrelevant feedback must be rejected. Return only valid JSON matching the requested schema."""

GENERATION_SYSTEM_PROMPT = """You are a technical resume strategist and ATS optimization expert. Rewrite the supplied resume using only facts explicitly present in the source resume and the approved evaluator improvement items. Never invent or infer employers, titles, dates, skills, tools, responsibilities, metrics, or outcomes. The server owns the LaTeX template: never return LaTeX, Markdown, commands, or formatting instructions. Return JSON only with a `resume_template` object containing `summary`, `skills`, `experience`, `education`, and `certifications`. `skills` is an array of `{label,items}`. `experience` is an array of `{title,company,dates,location,bullets}` and must preserve the supplied role count and exact bullet count per role. Each bullet must be concise, factual, and use X-Y-Z only where source evidence supports it. Preserve education and certifications as arrays. No introductory text or code fence."""

EVALUATION_SCHEMA = {"overall_score": 0, "category_scores": {"jd_alignment": 0, "technical_relevance": 0, "quantified_impact": 0, "clarity": 0, "ats_compatibility": 0, "factual_grounding": 0}, "executive_assessment": "", "improvement_items": [], "resolved_issue_ids": [], "partially_resolved_issue_ids": [], "unresolved_issue_ids": [], "score_delta": 0, "comparison": "", "feedback_relevant": True, "feedback_reason": ""}

def evaluator_prompt(resume: str, jd: str, history: list[dict], user_feedback: str = "", previous: dict | None = None) -> str:
    return f"{EVALUATOR_SYSTEM_PROMPT}\n\nOUTPUT JSON SCHEMA:\n{json.dumps(EVALUATION_SCHEMA)}\n\nRESUME:\n{resume}\n\nJOB DESCRIPTION:\n{jd}\n\nPREVIOUS EVALUATION:\n{json.dumps(previous or {})}\n\nUSER FEEDBACK:\n{user_feedback or 'None'}\n\nCONVERSATION HISTORY:\n{json.dumps(history)}"

def generation_prompt(resume: str, jd: str, items: list[dict], template_data: dict, feedback: str = "", model_name: str = "", layout_repair: str = "") -> str:
    return f"{GENERATION_SYSTEM_PROMPT}\n\nWRITER MODEL: {model_name}\n\nSOURCE RESUME:\n{resume}\n\nJOB DESCRIPTION:\n{jd}\n\nIMMUTABLE TEMPLATE STRUCTURE:\n{json.dumps(template_data)}\n\nAPPROVED IMPROVEMENT ITEMS:\n{json.dumps(items)}\n\nUSER FEEDBACK:\n{feedback or 'None'}\n\nLAYOUT CONSTRAINT:\n{layout_repair or 'Use concise professional language that fits the original page count.'}"
